# Generated by Django 3.1.2 on 2021-02-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Element',
            new_name='User',
        ),
    ]
