# Generated by Django 3.1.2 on 2021-02-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20210214_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('name', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('hierarchy', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api_app.usertype'),
        ),
    ]
